---
abstract: 'Link to device backups in RANCID/WebSVN'
author:
  - 'Oliver Gorwits <oliver@cpan.org>'
build_requires:
  Module::Build: '0.42'
  Test::Distribution: '0'
  Test::More: '0.88'
  Test::Perl::Critic: '0'
  Test::Pod: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0.06'
  Module::Build: '0.42'
dynamic_config: 0
generated_by: 'Module::Build version 0.4234, CPAN::Meta::Converter version 2.150010'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-NetdiscoX-Web-Plugin-RANCID
provides:
  App::NetdiscoX::Web::Plugin::RANCID:
    file: lib/App/NetdiscoX/Web/Plugin/RANCID.pm
    version: '3.000000'
requires:
  App::Netdisco: '2.042009'
  Dancer: '1.3132'
  File::ShareDir: '1.00'
resources:
  IRC: irc://irc.libera.chat/#netdisco
  MailingList: https://lists.sourceforge.net/lists/listinfo/netdisco-users
  bugtracker: https://github.com/netdisco/nd2-web-plugin-rancid/issues
  homepage: http://netdisco.org/
  license: http://opensource.org/licenses/BSD-3-Clause
  repository: https://github.com/netdisco/nd2-web-plugin-rancid
version: '3.000000'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
